obstacles:
  box1:
    size: [0.1, 0.1, 0.1]     # x,y,z in meters
    pose:
      xyz: [0.5, 0.0, 0.2]    # position relative to base_link
      rpy: [0.0, 0.0, 0.0]    # roll, pitch, yaw
    frame: base_link
